services:
    stef_simple_cms.postcode_manager:
        class: Stefanius\LocatieInformatieBundle\Manager\PostcodeManager
        arguments: ["@doctrine.orm.entity_manager", "@stef.slugifier"]

    stef_simple_cms.province_manager:
        class: Stefanius\LocatieInformatieBundle\Manager\ProvinceManager
        arguments: ["@doctrine.orm.entity_manager", "@stef.slugifier"]

    stef_simple_cms.zipcode_manager:
        class: Stefanius\LocatieInformatieBundle\Manager\ZipcodeManager
        arguments: ["@doctrine.orm.entity_manager", "@stef.slugifier"]

    stef_simple_cms.street_manager:
        class: Stefanius\LocatieInformatieBundle\Manager\StreetManager
        arguments: ["@doctrine.orm.entity_manager", "@stef.slugifier"]

    stef_simple_cms.city_manager:
        class: Stefanius\LocatieInformatieBundle\Manager\CityManager
        arguments: ["@doctrine.orm.entity_manager", "@stef.slugifier"]

    stef_simple_cms.municipality_manager:
        class: Stefanius\LocatieInformatieBundle\Manager\MunicipalityManager
        arguments: ["@doctrine.orm.entity_manager", "@stef.slugifier"]

    stef_simple_cms.page_manager:
        class: Stef\SimpleCmsBundle\Manager\PageManager
        arguments: ["@doctrine.orm.entity_manager"]
        calls:
            - [setSlugifier, ["@stef.slugifier"]]

    stef_simple_cms.entity_mapper:
        class: Stef\SimpleCmsBundle\EntityMapper\Mapper
        calls:
            - [addNewMapping, ["Postcode", "StefLocatieInformatieBundle", 'Stefanius\LocatieInformatieBundle\Entity', "@stef_simple_cms.postcode_manager"]]
            - [addNewMapping, ["Province", "StefLocatieInformatieBundle", 'Stefanius\LocatieInformatieBundle\Entity', "@stef_simple_cms.province_manager"]]
            - [addNewMapping, ["Municipality", "StefLocatieInformatieBundle", 'Stefanius\LocatieInformatieBundle\Entity', "@stef_simple_cms.municipality_manager"]]
            - [addNewMapping, ["City", "StefLocatieInformatieBundle", 'Stefanius\LocatieInformatieBundle\Entity', "@stef_simple_cms.city_manager"]]
            - [addNewMapping, ["ZipCode", "StefLocatieInformatieBundle", 'Stefanius\LocatieInformatieBundle\Entity', "@stef_simple_cms.zipcode_manager"]]
            - [addNewMapping, ["Page", "StefSimpleCmsBundle", 'Stef\SimpleCmsBundle\Entity', "@stef_simple_cms.page_manager"]]
            - [addNewMapping, ["Street", "StefLocatieInformatieBundle", 'Stef\StefLocatieInformatieBundle\Entity', "@stef_simple_cms.street_manager"]]

    stef_simple_cms.form_options:
        class: Stef\SimpleCmsBundle\Form\FormOptions
        calls:
            - [addOptions, ['page', 'body', [], 'ckeditor']]

    executor.convert_locations:
        class: Stefanius\LocatieInformatieBundle\Executor\ConvertExecutor
        arguments: ["@stef_simple_cms.postcode_manager", "@stef_simple_cms.province_manager", "@stef_simple_cms.municipality_manager", "@stef_simple_cms.city_manager", "@stef_simple_cms.zipcode_manager", "@stef_simple_cms.street_manager"]
        tags:
          - { name: tree_house.worker.executor }