stef_locatie_informatie_zipcode_redirect_human_format_1:
    path:     /postcode/{pnum}-{pchar}
    defaults: { _controller: StefLocatieInformatieBundle:Zipcode:redirect }
    requirements:
       pnum: \d{4}
       pchar: ^[A-Za-z]{2}

stef_locatie_informatie_zipcode_redirect_human_format_2:
    path:     /postcode/{pnum} {pchar}
    defaults: { _controller: StefLocatieInformatieBundle:Zipcode:redirect }
    requirements:
       pnum: \d{4}
       pchar: ^[A-Za-z]{2}

stef_locatie_informatie_zipcode_redirect_human_format_3:
    path:     /postcode/{pnum}%20{pchar}
    defaults: { _controller: StefLocatieInformatieBundle:Zipcode:redirect }
    requirements:
       pnum: \d{4}
       pchar: ^[A-Za-z]{2}

stef_locatie_informatie_zipcode_redirect_uppercase_format:
    path:     /postcode/{pnum}{pchar}
    defaults: { _controller: StefLocatieInformatieBundle:Zipcode:redirect }
    requirements:
       pnum: \d{4}
       pchar: ^[A-Z]{2}

stef_locatie_informatie_zipcode_show:
    path:     /postcode/{pnum}{pchar}
    defaults: { _controller: StefLocatieInformatieBundle:Zipcode:show }
    requirements:
       pnum: \d{4}
       pchar: ^[a-z]{2}

stef_locatie_informatie_zipcode_showarea:
    path:     /postcode/{pnum}
    defaults: { _controller: StefLocatieInformatieBundle:Zipcode:showarea }
    requirements:
       pnum: \d{4}

stef_locatie_informatie_zipcode_index:
    path:     /postcode
    defaults: { _controller: StefLocatieInformatieBundle:Zipcode:index }