services:
    stef_simple_cms.postcode_manager:
        class: Stef\LocatieInformatieBundle\Manager\PostcodeManager
        arguments: ["@doctrine.orm.entity_manager"]

    stef_simple_cms.province_manager:
        class: Stef\LocatieInformatieBundle\Manager\ProvinceManager
        arguments: ["@doctrine.orm.entity_manager"]

    stef_simple_cms.zipcode_manager:
        class: Stef\LocatieInformatieBundle\Manager\ZipcodeManager
        arguments: ["@doctrine.orm.entity_manager"]

    stef_simple_cms.city_manager:
        class: Stef\LocatieInformatieBundle\Manager\CityManager
        arguments: ["@doctrine.orm.entity_manager"]

    stef_simple_cms.municipality_manager:
        class: Stef\LocatieInformatieBundle\Manager\MunicipalityManager
        arguments: ["@doctrine.orm.entity_manager"]

    stef_simple_cms.entity_mapper:
        class: Stef\SimpleCmsBundle\EntityMapper\Mapper
        calls:
            - [addNewMapping, ["Postcode", "StefLocatieInformatieBundle", 'Stef\LocatieInformatieBundle\Entity', "@stef_simple_cms.postcode_manager"]]
            - [addNewMapping, ["Province", "StefLocatieInformatieBundle", 'Stef\LocatieInformatieBundle\Entity', "@stef_simple_cms.province_manager"]]
            - [addNewMapping, ["Municipality", "StefLocatieInformatieBundle", 'Stef\LocatieInformatieBundle\Entity', "@stef_simple_cms.municipality_manager"]]
            - [addNewMapping, ["City", "StefLocatieInformatieBundle", 'Stef\LocatieInformatieBundle\Entity', "@stef_simple_cms.city_manager"]]
            - [addNewMapping, ["ZipCode", "StefLocatieInformatieBundle", 'Stef\LocatieInformatieBundle\Entity', "@stef_simple_cms.zipcode_manager"]]

    stef_simple_cms.form_options:
        class: Stef\SimpleCmsBundle\Form\FormOptions

    executor.convert_locations:
        class: Stef\LocatieInformatieBundle\Executor\ConvertExecutor
        arguments: ["@stef_simple_cms.postcode_manager", "@stef_simple_cms.municipality_manager", "@stef_simple_cms.city_manager", "@stef_simple_cms.zipcode_manager"]
        tags:
          - { name: tree_house.worker.executor }