stef_locatie_informatie_1:
    resource: "@StefLocatieInformatieBundle/Resources/config/routing_indexpages.yml"

stef_locatie_informatie_2:
    resource: "@StefLocatieInformatieBundle/Resources/config/routing_province.yml"

stef_locatie_informatie_3:
    resource: "@StefLocatieInformatieBundle/Resources/config/routing_zipcodes.yml"

stef_locatie_informatie_4:
    resource: "@StefLocatieInformatieBundle/Resources/config/routing_municipalities.yml"

stef_locatie_informatie_5:
    resource: "@StefLocatieInformatieBundle/Resources/config/routing_cities.yml"

stef_locatie_informatie_homepage:
    path:     /
    defaults: { _controller: StefLocatieInformatieBundle:Default:index }

stef_locatie_informatie_locaties_or_lokaties:
    path:     /locatie-of-lokatie
    defaults: { _controller: StefLocatieInformatieBundle:StaticPage:locatieLokatie }

